In [37]:
import numpy as np

## Question 1 - 3

In [38]:
def bjj_points(points, bonus=2):
    return points + bonus

In [39]:
print(bjj_points(4))
print(bjj_points(4, bonus=0))

6
4


## Question 4 - 6

In [40]:
rounds = np.array([5, 5, 6, 4, 7])
rounds

array([5, 5, 6, 4, 7])

In [41]:
rounds.shape

(5,)

In [42]:
rounds.dtype

dtype('int64')

In [43]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
np.zeros(3)

array([0., 0., 0.])

## Question 7 - 9

In [45]:
calories = np.array([650, 800, 720, 900])

In [46]:
calories * 2

array([1300, 1600, 1440, 1800])

In [47]:
calories.mean()

np.float64(767.5)

In [48]:
calories.max()

np.int64(900)

In [49]:
[650, 800, 720, 900] * 2

[650, 800, 720, 900, 650, 800, 720, 900]

## Question 10 - 12

In [50]:
ratings = np.array([7.5, 9.0, 8.2, 6.8, 9.5, 8.9])

In [51]:
ratings[ratings > 8]

array([9. , 8.2, 9.5, 8.9])

In [52]:
ratings[:3]

array([7.5, 9. , 8.2])

## Question 13 - 15

In [58]:
minutes = np.arange(1, 13)
minutes

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [54]:
month = minutes.reshape(4, 3)

In [55]:
month

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [56]:
month.shape

(4, 3)

month.mean()